workflows:
  ios-debug-simulator:
    name: iOS Debug (Simulator)
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Ensure Podfile exists
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            pod init
            echo '✅ Podfile created.'
          else
            echo 'ℹ️ Podfile already exists.'
          fi
          sed -i '' '1s/^/platform :ios, '\''13.0'\''\n/' Podfile
          pod install
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/Runner.app
      - ios/Podfile
      - ios/Podfile.lock
      - ios/Runner.xcworkspace
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
